import type { Listing } from "./types";

/**
 * Mock marketplace harvests. These illustrate the product the marketing site
 * promises (direct picker-to-buyer sales); they are not real data. Prices sit
 * between the ~€2.4/kg farmgate and ~€13/kg retail cited on the How-it-works
 * page — i.e. the fairer direct price the app is meant to unlock. Photos are
 * real, CC-licensed iNaturalist images (see src/demo/photoCredits.ts).
 */
export const MOCK_LISTINGS: Listing[] = [
  {
    id: "lst-001",
    sp: "myrtillus",
    photo: "/listings/myrtillus-1.jpg",
    kg: 12,
    pricePerKg: 7.5,
    picker: "Aino Virtanen",
    rating: 4.9,
    municipality: "Kuusamo",
    listedOn: "2026-06-13",
    note: "Hand-picked on the fells above Ruka and frozen within hours of picking.",
  },
  {
    id: "lst-002",
    sp: "vitis-idaea",
    photo: "/listings/vitis-idaea-2.jpg",
    kg: 20,
    pricePerKg: 5.9,
    picker: "Eero Mäkinen",
    rating: 4.7,
    municipality: "Suomussalmi",
    listedOn: "2026-06-12",
    note: "Raked from old-growth pine forest. Firm, tart and clean — barely a leaf in the lot.",
  },
  {
    id: "lst-003",
    sp: "chamaemorus",
    photo: "/listings/chamaemorus-2.jpg",
    kg: 4,
    pricePerKg: 26,
    picker: "Liisa Korhonen",
    rating: 5.0,
    municipality: "Inari",
    listedOn: "2026-06-12",
    note: "Rare Lapland gold from the open mires. Limited quantity — first come, first served.",
  },
  {
    id: "lst-004",
    sp: "vesca",
    photo: "/listings/vesca-1.jpg",
    kg: 2.5,
    pricePerKg: 29,
    picker: "Sanna Laine",
    rating: 4.8,
    municipality: "Ilomantsi",
    listedOn: "2026-06-11",
    note: "Tiny, intensely sweet wild strawberries. Picked by hand and sold the same day.",
  },
  {
    id: "lst-005",
    sp: "idaeus",
    photo: "/listings/idaeus-1.jpg",
    kg: 6,
    pricePerKg: 11,
    picker: "Mikko Niemi",
    rating: 4.6,
    municipality: "Lieksa",
    listedOn: "2026-06-10",
    note: "Wild forest raspberries from sunny clearings near Koli. Fragrant and soft.",
  },
  {
    id: "lst-006",
    sp: "myrtillus",
    photo: "/listings/myrtillus-2.jpg",
    kg: 30,
    pricePerKg: 6.8,
    picker: "Janne Heikkinen",
    rating: 4.8,
    municipality: "Pudasjärvi",
    listedOn: "2026-06-10",
    note: "Bulk lot, ideal for juiceries and bakeries. Cold-stored, ready for pickup or freight.",
  },
  {
    id: "lst-007",
    sp: "vitis-idaea",
    photo: "/listings/vitis-idaea-1.jpg",
    kg: 15,
    pricePerKg: 6.2,
    picker: "Päivi Koskinen",
    rating: 4.9,
    municipality: "Kuhmo",
    listedOn: "2026-06-09",
    note: "Low-bruise, evenly ripe lingonberries. Cold-stored since the morning pick.",
  },
  {
    id: "lst-008",
    sp: "nigrum",
    photo: "/listings/nigrum-2.jpg",
    kg: 8,
    pricePerKg: 5.5,
    picker: "Ville Järvinen",
    rating: 4.4,
    municipality: "Kittilä",
    listedOn: "2026-06-08",
    note: "Antioxidant-rich crowberry from the northern heath. Great for juice and powder.",
  },
  {
    id: "lst-009",
    sp: "uliginosum",
    photo: "/listings/uliginosum-1.jpg",
    kg: 10,
    pricePerKg: 6.0,
    picker: "Helena Nieminen",
    rating: 4.5,
    municipality: "Sodankylä",
    listedOn: "2026-06-07",
    note: "Bog bilberry from the mire edges — soft, mild and milder in colour than mustikka.",
  },
  {
    id: "lst-010",
    sp: "juniperus",
    photo: "/listings/juniperus-1.jpg",
    kg: 3,
    pricePerKg: 14,
    picker: "Antti Salminen",
    rating: 4.7,
    municipality: "Rovaniemi",
    listedOn: "2026-06-06",
    note: "Aromatic ripe juniper berries for gin, game and gravlax. Dried to order.",
  },
];
